POST http://localhost:8081/task-management
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJmYXRtYVVzZXIiLCJleHAiOjE3NDg1NzY2NjYsImlhdCI6MTc0ODU0MDY2Nn0.yEEMnaLwO-w34XB5GZp_xb74TUGR220qEySAmbTiUHQ
Content-Type: application/json

{
  "status": "TO_DO",
  "title": "task2",
  "description": "task2",
  "priority": "HIGH",
  "createdBy": "Fatma",
  "dueDate": "2025-05-29T01:16:35.787897Z"
}